### ISSUE TITLE
画像とテストケースの対応

### ISSUE THREAD

**Issue by st-ishr** [hifive/hifive-pitalium-jenkins-plugin#17]
一覧表示している画像を，テストケースに対応させる方法の模索

**Comment by sakaim** [comment]
以下の方針で対応する。
* 画像一覧をテストケース別にテーブルで整理する
* 一覧絞込み時に対応する画像をハイライトさせる

**Comment by sakaim** [comment]
https://github.com/hifive/hifive-pitalium-jenkins-plugin/pull/23
で対応済。
